
- name: Remove Windows Defender
  win_feature:
    name: Windows-Defender
    state: absent
  register: win_feature

- name: Reboot if required after removing Window Defender
  win_reboot:
  when: win_feature.reboot_required

