
- name: Download Git for Windows
  win_get_url:
    url: https://github.com/git-for-windows/git/releases/download/v2.36.1.windows.1/Git-2.36.1-64-bit.exe
    dest: c:\windows\temp\Git-2.36.1-64-bit.exe

- name: Install Git for Windows
  win_command: c:\windows\temp\Git-2.36.1-64-bit.exe /VERYSILENT /NORESTART

- name: Reboot after Git installation
  win_reboot:

- name: Configure git to accept long paths
  win_command: git config --system core.longpaths true

- name: Add Git to PATH
  win_path:
    elements:
      - c:\Program Files\Git\cmd

