---
# tasks file for OCaml

#- name: Open HKCU for editing
#  win_command: >-
#    REG LOAD "hku\temp" "c:\Users\Default User\NTUSER.DAT"
#
#- name: Add Run to Start Menu
#  win_command: >-
#    REG ADD "hku\temp\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v ForceRunOnStartMenu /t REG_DWORD /d 1 /f
#
#- name: Close HKCU
#  win_command: >-
#    REG UNLOAD "hku\temp"

- name: Create layout.xml
  win_copy:
    dest: c:\Windows\layout.xml
    content: |
      <LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
        <LayoutOptions StartTileGroupCellWidth="6" />
        <DefaultLayoutOverride>
          <StartLayoutCollection>
            <defaultlayout:StartLayout GroupCellWidth="6">
              <start:Group Name="">
                <start:DesktopApplicationTile Size="2x2" Column="0" Row="2" DesktopApplicationID="Microsoft.VisualStudioCode" />
                <start:DesktopApplicationTile Size="2x2" Column="2" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\GVim.lnk" />
                <start:DesktopApplicationTile Size="2x2" Column="4" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Emacs.lnk" />
                <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationID="MSEdge" />
                <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationID="Microsoft.AutoGenerated.{A5453931-F805-F45B-7147-C95AEAFB19D3}" />
                <start:DesktopApplicationTile Size="2x2" Column="4" Row="0" DesktopApplicationID="Microsoft.Windows.Shell.RunDialog" />
              </start:Group>
            </defaultlayout:StartLayout>
          </StartLayoutCollection>
        </DefaultLayoutOverride>
      </LayoutModificationTemplate>

- name: Set the Start Menu ...
  win_command: >-
    REG ADD "HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Explorer" /v LockedStartLayout /t REG_DWORD /d 1 /f

- name: ... to c:\windows\layout.xml
  win_command: >-
    REG ADD "HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Explorer" /v StartLayoutFile /t REG_EXPAND_SZ /d "c:\windows\layout.xml" /f

- name: Disable Windows Defender
  win_shell: Set-MpPreference -DisableRealtimeMonitoring $true

